version: '2.4'  
services:   
  master:
    cpuset: "3" 
    # cpus: 0.31
    build: master-worker
    restart: on-failure
    container_name: master
    hostname: master
    expose:        
    - "12345"      
    volumes:             
    - "./code:/root/code"
    networks:
      tensorNet:
          ipv4_address: 172.10.0.2   
     
  worker1:
    cpuset: "6,7" 
    # cpus: 0.31
    build: worker
    hostname: worker1
    expose:        
    - "23456"      
    volumes:             
    - "./code:/root/code"  
    links:
    - master
    networks:
      - tensorNet
  worker2:
    cpuset: "4,5" 
    # cpus: 0.31

    build: worker
    hostname: worker2
    expose:
    - "14739"
    volumes:
    - "./code:/root/code"
    links:
    - master
    networks:
    - tensorNet


networks:
  tensorNet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24
