version: '3.8'  
services:   
  chief:   
    build: chief-worker
    restart: on-failure
    container_name: chief
    hostname: chief     
    expose:        
    - "12345"      
    volumes:             
    - "./code:/root/code"
    networks:
      tensorNet:
          ipv4_address: 172.10.0.2   
     
  worker:      
    build: worker    
    expose:        
    - "23456"      
    volumes:             
    - "./code:/root/code"  
    links:
    - chief
    networks:
      - tensorNet


networks:
  tensorNet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24